apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quiz-frontend
  labels:
    app: quiz
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: quiz-app
        tier: frontend
    spec:
      containers:
      - name: quiz-frontend
        image: gcr.io/[GCLOUD_PROJECT]/quiz-frontend
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
        env:
          - name: GCLOUD_PROJECT
            value: [GCLOUD_PROJECT]
          - name: GCLOUD_BUCKET
            value: [GCLOUD_PROJECT]-media
          - name: NODE_ENV
            value: production