# config-management.yaml
apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: onprem.k8s.local

--
# rootSync
apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: root-sync
  namespace: config-management-system
spec:
  sourceType: git
  git:
    repo: ssh://[qwiklabs-user-email]@source.developers.google.com:2022/p/[qwiklabs-project]/r/anthos_config
    branch: master
    auth: ssh
    secretRef:
      name: git-creds