# Copyright 2017 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
swagger: "2.0"
info:
  title: "Recommendations"
  description: "Get recommended items for a User given their ID."
  version: "1.0.0"
# This field will be replaced by the deploy_api.sh script.
host: "YOUR-PROJECT-ID.appspot.com"
schemes:
  - "https"
paths:
  "/recommendation":
    get:
      description: "Get recommended items for a User given their ID."
      operationId: "recommendation"
      parameters:
        -
          name: userId
          in: query
          required: true
          type: integer
        -
          name: numRecs
          in: query
          required: false
          type: integer
      responses:
        200:
          description: "Success."
          schema:
            type: string
        400:
          description: "The User Id is not found or missing."
